<?php if (!$order): ?><div class="alert alert-danger">Pedido não encontrado.</div><?php else: ?>
<div class="row g-4">
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h4 mb-1">Pedido #<?= e((string) $order['id']) ?></h2><p class="text-muted mb-0">Tracking: <?= e($order['tracking_code']) ?></p></div><span class="badge text-bg-dark"><?= e($order['status']) ?></span></div><p><?= e($order['description']) ?></p><div class="row g-3 mt-1"><div class="col-md-6"><strong>Cliente:</strong> <?= e($order['client_name']) ?></div><div class="col-md-6"><strong>Telefone:</strong> <?= e($order['client_phone']) ?></div><div class="col-md-6"><strong>Serviço:</strong> <?= e($order['service_type'] ?: 'Personalizado') ?></div><div class="col-md-6"><strong>Valor:</strong> <?= e(number_format((float) $order['amount'],2)) ?> MZN</div></div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h5">Ações rápidas</h3><form method="post" action="/admin/pedidos/<?= e((string) $order['id']) ?>/status" class="row g-3 mb-4"><?= \App\Core\Csrf::field() ?><div class="col-md-8"><select name="status" class="form-select"><?php foreach (\App\Models\Order::STATUSES as $status): ?><option value="<?= e($status) ?>"><?= e($status) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><button class="btn btn-dark w-100">Atualizar status</button></div></form><form method="post" action="/admin/pedidos/<?= e((string) $order['id']) ?>/upload-final" enctype="multipart/form-data" class="row g-3"><?= \App\Core\Csrf::field() ?><div class="col-md-8"><input type="file" name="edited_image" class="form-control" required></div><div class="col-md-4"><button class="btn btn-success w-100">Enviar foto final</button></div></form></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h3 class="h5">Revisões</h3><?php if (empty($order['revisions'])): ?><p class="text-muted mb-0">Nenhuma revisão registada.</p><?php else: ?><div class="d-grid gap-3"><?php foreach ($order['revisions'] as $revision): ?><div class="border rounded p-3"><strong><?= e($revision['status']) ?></strong><p class="mb-1 small"><?= e($revision['client_message']) ?></p><?php if ($revision['admin_response']): ?><div class="small text-muted">Resposta: <?= e($revision['admin_response']) ?></div><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></div></div>
    </div>
    <div class="col-lg-4">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h6 text-uppercase text-muted">Foto principal</h3><img src="<?= e(media_url($order['primary_image_path'])) ?>" class="img-fluid rounded" alt="Principal"></div></div>
        <?php if ($order['edited_image_path']): ?><div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h6 text-uppercase text-muted">Foto final</h3><img src="<?= e(media_url($order['edited_image_path'])) ?>" class="img-fluid rounded" alt="Final"></div></div><?php endif; ?>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h3 class="h6 text-uppercase text-muted">Transação</h3><?php if (!empty($order['transaction'])): ?><ul class="list-unstyled mb-0"><li><strong>Ref:</strong> <?= e($order['transaction']['debito_reference']) ?></li><li><strong>Status:</strong> <?= e($order['transaction']['status']) ?></li><li><strong>Valor:</strong> <?= e(number_format((float) $order['transaction']['amount'],2)) ?> MZN</li></ul><?php else: ?><p class="text-muted mb-0">Sem transação associada.</p><?php endif; ?></div></div>
    </div>
</div>
<?php endif; ?>
