<?php if (!$order): ?><div class="alert alert-danger">Pedido não encontrado.</div><?php else: ?>
<div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4">
    <div>
        <h2 class="h4 mb-1">Pedido #<?= e((string) $order['id']) ?></h2>
        <p class="text-muted mb-0">Tracking <?= e($order['tracking_code']) ?> · Criado em <?= e($order['created_at']) ?></p>
    </div>
    <span class="badge text-bg-dark fs-6"><?= e($order['status']) ?></span>
</div>

<?php if (!empty($flash)): ?><div class="alert alert-success"><?= e($flash) ?></div><?php endif; ?>
<?php if (!empty($error)): ?><div class="alert alert-danger"><?= e($error) ?></div><?php endif; ?>

<div class="row g-4 mb-4">
    <div class="col-lg-8">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h5 mb-3">Resumo do pedido</h3><p class="mb-4"><?= e($order['description']) ?></p><div class="row g-3"><div class="col-md-6"><strong>Cliente:</strong><div><?= e($order['client_name']) ?></div></div><div class="col-md-6"><strong>Telefone:</strong><div><?= e($order['client_phone']) ?></div></div><div class="col-md-6"><strong>Serviço:</strong><div><?= e($order['service_type'] ?: 'Personalizado') ?></div></div><div class="col-md-6"><strong>Valor:</strong><div><?= e(number_format((float) $order['amount'], 2)) ?> MZN</div></div><div class="col-md-6"><strong>Revisões usadas:</strong><div><?= e((string) $order['revisions_used']) ?></div></div><div class="col-md-6"><strong>Pagamento confirmado:</strong><div><?= e($order['payment_confirmed_at'] ?? 'Ainda não') ?></div></div></div></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h5 mb-3">Ações rápidas</h3><form method="post" action="/admin/pedidos/<?= e((string) $order['id']) ?>/status" class="row g-3 mb-4"><?= \App\Core\Csrf::field() ?><div class="col-md-8"><select name="status" class="form-select"><?php foreach (\App\Models\Order::STATUSES as $status): ?><option value="<?= e($status) ?>" <?= $order['status'] === $status ? 'selected' : '' ?>><?= e($status) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><button class="btn btn-dark w-100">Atualizar status</button></div></form><form method="post" action="/admin/pedidos/<?= e((string) $order['id']) ?>/upload-final" enctype="multipart/form-data" class="row g-3"><?= \App\Core\Csrf::field() ?><div class="col-md-8"><input type="file" name="edited_image" class="form-control" required></div><div class="col-md-4"><button class="btn btn-success w-100">Enviar foto final</button></div></form></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h5 mb-3">Galeria do pedido</h3><div class="row g-3"><div class="col-md-6"><div class="border rounded-4 p-3"><div class="small text-muted mb-2">Foto principal</div><img src="<?= e(media_url($order['primary_image_path'])) ?>" class="img-fluid rounded" alt="Principal"></div></div><?php foreach ($order['extra_images'] as $image): ?><div class="col-md-6"><div class="border rounded-4 p-3"><div class="small text-muted mb-2">Imagem adicional #<?= e((string) $image['sort_order']) ?></div><img src="<?= e(media_url($image['file_path'])) ?>" class="img-fluid rounded" alt="Extra"></div></div><?php endforeach; ?><?php if ($order['edited_image_path']): ?><div class="col-12"><div class="border rounded-4 p-3 bg-light"><div class="small text-muted mb-2">Resultado final entregue</div><img src="<?= e(media_url($order['edited_image_path'])) ?>" class="img-fluid rounded" alt="Final"></div></div><?php endif; ?></div></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h3 class="h5 mb-3">Histórico de revisões</h3><?php if (empty($order['revisions'])): ?><p class="text-muted mb-0">Nenhuma revisão registada.</p><?php else: ?><div class="d-grid gap-3"><?php foreach ($order['revisions'] as $revision): ?><div class="border rounded-4 p-3"><div class="d-flex justify-content-between"><strong><?= e($revision['status']) ?></strong><span class="small text-muted"><?= e($revision['created_at']) ?></span></div><p class="mb-1 mt-2"><?= e($revision['client_message']) ?></p><?php if ($revision['admin_response']): ?><div class="small text-muted">Resposta do admin: <?= e($revision['admin_response']) ?></div><?php endif; ?></div><?php endforeach; ?></div><?php endif; ?></div></div>
    </div>
    <div class="col-lg-4">
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h6 text-uppercase text-muted">Transação principal</h3><?php if (!empty($order['transaction'])): ?><ul class="list-unstyled mb-0"><li><strong>Ref:</strong> <?= e($order['transaction']['debito_reference']) ?></li><li><strong>Status:</strong> <?= e($order['transaction']['status']) ?></li><li><strong>Gateway:</strong> <?= e($order['transaction']['gateway_status'] ?? 'n/d') ?></li><li><strong>Valor:</strong> <?= e(number_format((float) $order['transaction']['amount'], 2)) ?> MZN</li><li><strong>Última verificação:</strong> <?= e($order['transaction']['last_checked_at'] ?? 'n/d') ?></li></ul><?php else: ?><p class="text-muted mb-0">Sem transação associada.</p><?php endif; ?></div></div>
        <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h3 class="h6 text-uppercase text-muted">Histórico de transações</h3><?php if (empty($order['transactions'])): ?><p class="text-muted mb-0">Nenhuma transação registada.</p><?php else: ?><div class="d-grid gap-2"><?php foreach ($order['transactions'] as $tx): ?><div class="border rounded-4 p-3"><div class="fw-semibold small"><?= e($tx['debito_reference']) ?></div><div class="small text-muted"><?= e($tx['status']) ?> · <?= e(number_format((float) $tx['amount'], 2)) ?> MZN</div></div><?php endforeach; ?></div><?php endif; ?></div></div>
        <div class="card border-0 shadow-sm"><div class="card-body p-4"><h3 class="h6 text-uppercase text-muted">Auditoria</h3><?php if (empty($order['activities'])): ?><p class="text-muted mb-0">Sem logs administrativos.</p><?php else: ?><div class="d-grid gap-3"><?php foreach ($order['activities'] as $activity): ?><div class="border rounded-4 p-3"><div class="fw-semibold small"><?= e($activity['action']) ?></div><div class="small text-muted"><?= e($activity['description']) ?></div><div class="small text-muted"><?= e($activity['created_at']) ?></div></div><?php endforeach; ?></div><?php endif; ?></div></div>
    </div>
</div>
<?php endif; ?>
