<div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4">
    <div><span class="eyebrow text-primary">Relatórios</span><h2 class="h3 mb-1">Visão gerencial</h2><p class="text-muted mb-0">Acompanhe operação, satisfação, conversão e serviços mais solicitados.</p></div>
</div>
<div class="admin-card mb-4"><form class="row g-3"><div class="col-md-4"><label class="form-label fw-semibold">De</label><input type="date" name="start_date" class="form-control" value="<?= e($filters['start_date']) ?>"></div><div class="col-md-4"><label class="form-label fw-semibold">Até</label><input type="date" name="end_date" class="form-control" value="<?= e($filters['end_date']) ?>"></div><div class="col-md-4 d-grid"><label class="form-label">&nbsp;</label><button class="btn btn-primary"><i class="fa-solid fa-chart-column me-2"></i>Atualizar relatório</button></div></form></div>
<div class="row g-4 mb-4">
    <div class="col-md-6"><div class="admin-stat-card"><span class="stat-icon"><i class="fa-solid fa-face-smile"></i></span><div class="text-muted small">Taxa de satisfação</div><div class="metric-value"><?= e(number_format($satisfactionRate, 2)) ?>%</div></div></div>
    <div class="col-md-6"><div class="admin-stat-card"><span class="stat-icon"><i class="fa-solid fa-money-check-dollar"></i></span><div class="text-muted small">Taxa de conversão de pagamento</div><div class="metric-value"><?= e(number_format($paymentConversionRate, 2)) ?>%</div></div></div>
</div>
<div class="row g-4">
    <div class="col-lg-6"><div class="table-card p-0 overflow-hidden"><div class="p-4 pb-0"><h3 class="h5 mb-3"><i class="fa-solid fa-chart-bar me-2 text-primary"></i>Pedidos por status</h3></div><div class="table-responsive px-3 pb-3"><table class="table"><tbody><?php foreach ($ordersByStatus as $row): ?><tr><td><?= e($row['status']) ?></td><td><?= e((string) $row['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
    <div class="col-lg-6"><div class="table-card p-0 overflow-hidden"><div class="p-4 pb-0"><h3 class="h5 mb-3"><i class="fa-solid fa-layer-group me-2 text-primary"></i>Serviços mais solicitados</h3></div><div class="table-responsive px-3 pb-3"><table class="table"><tbody><?php foreach ($mostRequestedServices as $row): ?><tr><td><?= e($row['service_type']) ?></td><td><?= e((string) $row['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
    <div class="col-lg-6"><div class="table-card p-0 overflow-hidden"><div class="p-4 pb-0"><h3 class="h5 mb-3"><i class="fa-solid fa-calendar-week me-2 text-primary"></i>Pedidos por período</h3></div><div class="table-responsive px-3 pb-3"><table class="table"><tbody><?php foreach ($ordersByPeriod as $row): ?><tr><td><?= e($row['period']) ?></td><td><?= e((string) $row['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
    <div class="col-lg-6"><div class="table-card p-0 overflow-hidden"><div class="p-4 pb-0"><h3 class="h5 mb-3"><i class="fa-solid fa-star me-2 text-primary"></i>Feedback por período</h3></div><div class="table-responsive px-3 pb-3"><table class="table"><tbody><?php foreach ($feedbackByPeriod as $row): ?><tr><td><?= e($row['period']) ?></td><td><?= e((string) $row['total']) ?></td><td><?= e(number_format((float) $row['average_rating'], 1)) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
    <div class="col-lg-6"><div class="table-card p-0 overflow-hidden"><div class="p-4 pb-0"><h3 class="h5 mb-3"><i class="fa-solid fa-rotate me-2 text-primary"></i>Pedidos com revisão</h3></div><div class="table-responsive px-3 pb-3"><table class="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Qtd.</th></tr></thead><tbody><?php foreach ($ordersWithRevisions as $row): ?><tr><td>#<?= e((string) $row['id']) ?></td><td><?= e($row['client_name']) ?></td><td><?= e((string) $row['revision_count']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
    <div class="col-lg-6"><div class="table-card p-0 overflow-hidden"><div class="p-4 pb-0"><h3 class="h5 mb-3"><i class="fa-solid fa-circle-check me-2 text-primary"></i>Aprovados sem revisão</h3></div><div class="table-responsive px-3 pb-3"><table class="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Aprovado em</th></tr></thead><tbody><?php foreach ($approvedWithoutRevision as $row): ?><tr><td>#<?= e((string) $row['id']) ?></td><td><?= e($row['client_name']) ?></td><td><?= e($row['approved_at'] ?? 'n/d') ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div>
